apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment #The name of the Kubernetes Deployment to be created in the Kubernetes cluster
  labels:
    app: next-app
spec:
  replicas: 1 #The number of pods to be created in the Kubernetes cluster for the Next.js application container
  selector:
    matchLabels:
      app: next-app
  template:
    metadata:
      labels:
        app: next-app 
    spec:
      containers:
      - name: next-app #The name of the next.js application container
        image: quancyber/next-app:latest #The Docker image for building the Next.js application container
        ports:
        - containerPort: 3000 #The port for the Next.js application   container